services:
  frontend:
    build: ./grace-connect-frontend
    container_name: frontend
    restart: always
    env_file:
      - ./grace-connect-frontend/.env.production
    networks:
      - graceconnect-net

  backend:
    build: ./grace-connect-backend
    container_name: backend
    restart: always
    env_file:
      - ./grace-connect-backend/.env.production
    networks:
      - graceconnect-net

  nginx:
    image: nginx:latest
    container_name: graceconnect-nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - frontend
      - backend
    networks:
      - graceconnect-net

networks:
  graceconnect-net:
    driver: bridge