services:
  frontend:
    build: ./grace-connect-frontend
    container_name: frontend
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - backend
    env_file:
      - ./grace-connect-backend/.env.production

  backend:
    build: ./grace-connect-backend
    container_name: backend
    restart: always
    ports:
      - "5000:5000"
    env_file:
      - ./grace-connect-backend/.env.production
  
  nginx:
    image: nginx:latest
    container_name: graceconnect-nginx-1
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - frontend
      - backend