server {
    listen 80;
    server_name graceconnect.au www.graceconnect.au;

    location / {
        proxy_pass http://frontend:3000;
    }
}

server {
    listen 80;
    server_name api.graceconnect.au;

    location / {
        proxy_pass http://backend:5000;
    }
}